appVersion: v1
kind: Secret
metadata:
  name: mysecrets
  labels:
    app: my-django-app
    chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
    release: '{{ .Release.Name }}'
    heritage: '{{ .Release.Service }}'
type: Opaque
data:
  user: {{ .Values.user | b64enc | quote }}
  password: {{ .Values.password | b64enc | quote }}
