apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-django-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Galyusha/S25-core-course-labs.git
    targetRevision: lab12
    path: k8s/my-django-app
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}